intercom/intercom-cordova

README.md
there is a hyphen missing in the Readme
=> added missing hyphen

plugin.xml, src/android/build-extras-intercom.gradle
For description of the problem and solutiont, see: https://issues.apache.org/jira/browse/CB-10014
I opened an issue about it here: https://github.com/intercom/intercom-cordova/issues/36
=> Fixes provider conflicts (-505 INSTALL_FAILED_CONFLICTING_PROVIDER)

src/android/IntercomBridge.java, src/ios/IntercomBridge.h, src/ios/IntercomBridge.m, www/intercom.js
Adding the iOS only feature setPreviewPadding to iOS and adding a console error for it being called in Android
=> Adding setPreviewPadding

src/android/IntercomBridge.java
This will fix https://github.com/intercom/intercom-cordova/issues/55
=> Removed race condition in pluginInitialize

src/ios/IntercomBridge.h, src/ios/IntercomBridge.m
=> added displayMessenger for iOS

src/android/IntercomBridge.java, src/ios/IntercomBridge.h, src/ios/IntercomBridge.m, www/intercom.js
- Added JS API for hiding the Intercom Messenger
=> Hide Messenger API

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
This release will fix https://github.com/intercom/intercom-cordova/issues/97.
=> Version 3.0.13

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/Intercom.framework/Versions/A/Headers/Intercom.h, src/ios/IntercomBridge.m
- Updated Intercom for iOS to [3.0.17](https://github.com/intercom/intercom-ios/releases/tag/3.0.17).
=> Release 3.0.15

circle.yml
=> Bump Node version on CircleCI

circle.yml
Allows automated release process
=> Release tagged versions through CI

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
=> Release 3.0.23

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/android/intercom.gradle, src/ios/IntercomBridge.m
Android release notes here: https://github.com/intercom/intercom-android/releases/tag/3.0.18
=> Bump version and update Android library to 3.0.18

CHANGELOG.md, README.md, circle.yml, package.json, plugin.xml, src/android/IntercomBridge.java, src/android/intercom.gradle, src/ios/Intercom.framework/Versions/A/Headers/Intercom.h, src/ios/IntercomBridge.m
Updates to latest version of Android and iOS Messengers
=> Release 3.0.26

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
* Fixed build error reported in [#180](https://github.com/intercom/intercom-cordova/issues/180).
=> Release 3.2.1

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
* Prevent unsafe versions of the Support Library being used to fix [#182](https://github.com/intercom/intercom-cordova/issues/182)
=> Release 3.2.2

CHANGELOG.md, Example/www/index.html, Example/www/js/index.js, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.h, intercom-plugin/src/ios/IntercomBridge.m, intercom-plugin/www/intercom.js
* Updated Intercom for Android to 4.1.x
* Updated Intercom for iOS to 4.1.x
* Added `intercom.logout()`.
* Added diagnostic messages for Android build errors.
=> Update to 4.1.0

circle.yml
This should make the release script work properly
=> Fix release script

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m
Fixed issue with diagnostic messages on Android: [#219](https://github.com/intercom/intercom-cordova/issues/219).
=> Bump version to 4.1.1

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m
Further fixes to issue with diagnostic messages on Android: [#219](https://github.com/intercom/intercom-cordova/issues/219)
=> Bump version to 4.1.2

intercom-plugin/plugin.xml
Addresses issue documented here: #248
=> Change hook for checkForUpdate to be after_prepare

intercom-plugin/package.json
This was missed in https://github.com/intercom/intercom-cordova/pull/254
=> Bump version in package.json

README.md
We are moving our support to our Intercom Developer Hub.
=> Migrating Customer Support

circle.yml, intercom-plugin/scripts/checkForUpdate.js, intercom-plugin/scripts/prepareCocoaPods.js
Use api-28 image for Circle CI
& from https://github.com/intercom/intercom-cordova/pull/269
> Cordova 9 removed support for built-in module
resolution in place of standard approach.
=> Update Android image for Circle CI

Example/config.xml, Example/package-lock.json, Example/package.json, README.md, circle.yml, intercom-plugin/scripts/checkForUpdate.js, intercom-plugin/scripts/prepareCocoaPods.js
Hard code to 8.x.x for iOS builds
=> Fixing builds

intercom-plugin/package.json
- Added support for Cordova 9.0
=> Release 7.0.0

Example/README.md, Example/config.xml, Example/package.json, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
In this PR I'm 
- updating to cordova-android 8.0.0 and cordova-ios 5.0.0
- removing GCM as [Google has removed GCM](https://developers.google.com/cloud-messaging/faq)
- update Firebase version 
- fixed an issue with push notifications on Android
- updating our Example app to use the newer versions of Cordova
- updating `intercom.gradle` to use the latest version of our Android SDK 
I successfully tested these changes in our Example app on both iOS and Android.
=> Update to cordova-android 8.0.0 and cordova-ios 5.0.0, remove GCM

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m
* Updated to cordova-android 8.0.0 and cordova-ios 5.0.0
* Removed GCM as [Google has removed GCM](https://developers.google.com/cloud-messaging/faq)
* Updated Firebase version and fixed an issue with Android push notifications not displaying
* Updated our Example app to use the newer versions of Cordova
* Now using the latest versions of the Intercom [Android SDK](https://github.com/intercom/intercom-android/releases) and [iOS SDK](https://github.com/intercom/intercom-android/releases) with support for Custom Bots!
Custom Bots can now be targeted specifically to your mobile app users! Whether your users are on the web or mobile, Custom Bots now work cross-platform to automate and accelerate growth.
Use our bots to provide better personalization at scale during critical moments of the …
=> Release 7.1.0

circle.yml, intercom-plugin/src/android/intercom.gradle
Hardcode Intercom Android sdk version 5.4.1 as it's the last version for API 28
=> Use Intercom Android 5.4.1 instead of 5.+

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m
Update to use Intercom Android 5.4.1
=> Release version 7.1.1

circle.yml
Seeing some build errors, updating to newer node version
=> Update node version

circle.yml
https://www.npmjs.com/package/npm-cli-login
=> Fix publish script

CHANGELOG.md, Example/package-lock.json, Example/package.json, README.md, circle.yml, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
**v9.0.0 of the Cordova plugin supports the latest version (7.1.0) of the Intercom mobile SDK. We’re introducing a fantastic new mobile engagement feature called Mobile Carousels. We’ve also added support for closed conversations, as well as a number of fixes and performance improvements.**
Bring your best features. We'll bring the spotlight. Use [Mobile Carousels](https://intercom.com/mobile) to connect with app users at every touchpoint—show them around, provide support, and highlight features you know they'll love.
Mobile Carousels are a multi-screen message designed to feel right at home in your mobile app. 
* Rich multi-screen messages.
* Highly customizable, right inside Intercom.
* Request device permissions like push notifications, camera, location and more.
* Deep link into your …
=> Release version 9.0.0

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/intercom.gradle
- Updated Intercom SDK iOS version to 9.0.0
=> Release 9.4.0

circle.yml
- Updated CircleCI config to use Xcode 13.0
=> iOS 15 Support

intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.h, intercom-plugin/src/ios/IntercomBridge.m, intercom-plugin/www/intercom.js
https://github.com/ionic-team/ionic-native/pull/3572
=> feat: add setBottomPadding

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
* The Intercom Cordova plugin has been updated to use the latest version (v10.1.0) of the Intercom iOS and Android SDK
* Updated to cordova-android 10.0.0
=> Release 10.1.0

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
Updated to use the latest version of the Intercom iOS (v10.3.0) and Android SDK (v10.2.0)
=> release 10.2.0

Example/config.xml, README.md, circle.yml, intercom-plugin/plugin.xml, intercom-plugin/src/ios/IntercomBridge.m
- Updated to Intercom iOS SDK 11.0.0.
- The minimum deployment version for iOS is now iOS 13.
=> Release 11.0.0

Example/config.xml, Example/package.json, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/intercom.gradle, runAndroidSample.sh, runiOSSample.sh
:rocket: Enhancements
- We've added Suggested Articles to your Homescreen! Provide a better self-serve experience to your users by enabling them to answer their question before they reach out to a teammate.
=> Updated to v11.1.0

CHANGELOG.md, Example/config.xml, README.md, circle.yml, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
- Updated to use Intercom version 12.0.0 for both Android and iOS.
- Updated CHANGELOG and README to reflect the update.
=> Release 12.0.0

CHANGELOG.md, Example/config.xml, circle.yml, intercom-plugin/package.json, intercom-plugin/src/android/intercom.gradle
Updates Intercom Android to support Android 13
=> Release 13.1.0

CHANGELOG.md
🚀  Enhancements
* Updated Intercom Cordova Plugin to support the latest versions of the core iOS and Android SDKs.
* Updated to the latest versions of `cordova`, `cordova-android` and `cordova-ios`.
* As this is a major release, we have deprecated a number of APIs and added some new ones. The deprecated APIs will continue to work for the next few versions of the plugin, after which they will be removed fully.
=> Release 14.0.0

CHANGELOG.md, intercom-plugin/package-lock.json, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/scripts/prepareCocoaPods.js, intercom-plugin/src/android/intercom.gradle
🚀 Enhancements
* It is now possible to send push notifications to the Simulator. (iOS)
🐛 Bug Fixes
* Fixed an issue where it was not possible to close modal view that was opened from a Messenger App. (iOS)
* The message composer is now always displayed on the conversation screen when appropriate.(iOS)
* When a conversation is closed, form entry is disabled on the conversation screen. (iOS & Android)
* Made some minor UI bug fixes. (iOS)
* Fixed the issue where push open stats weren’t tracked correctly. (Android)
=> Release 14.0.1

CHANGELOG.md, Example/package-lock.json, Example/package.json, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/intercom.gradle
🚀 Enhancements
* Improved delineation between AI Agents and bots.
* New handover experience from AI Agents to teammates.
* Added Privacy Policy in the conversation screen.
* Special notice now supports multiple languages.
* Intercom SDK now targets Android 15 (API level 35) (Android)
* Added edge-to-edge support (Android)
=> Release 14.1.0
