intercom/intercom-cordova

plugin.xml
With other plugins including `om.google.android.gms:play-services-[libname]:+`, the build would fail with the error reported in https://github.com/intercom/intercom-cordova/issues/31.
I'm not sure why this happens, but I suspect that mixed library versions is a no-go.
=> Changes play-services-gcm version from 8.1.0 to +

plugin.xml
This fixes a compile issue in the latest version of the plugin, where the Intercom dependency Photos.framework is not added to build.
=> Add Photos framework, required by bundled Intercom framework.

.travis.yml, circle.yml
This adds the necessary configuration to build the Example app on CircleCI (Android) and TravisCI (iOS).
=> Build Example app on Travis CI/CircleCI

plugin.xml
After reconsidering the best approach, this PR adds `NSPhotoLibraryUsageDescription` as was suggested in #91.
=> Add NSPhotoLibraryUsageDescription to Info.plist

src/android/IntercomBridge.java
Initialisation code is now more compatible with version 3.0.13 of the Android Messenger.
Also uses `Log.e` for logging instead of `System.err`.
=> Better initialisation on Android

src/android/intercom.gradle, src/android/setupFcm.js
This simplifies our FCM implementation by reducing our reliance on hooks by including the classpath directly from our own gradle file.
Related to https://github.com/intercom/intercom-cordova/issues/148.
The hook is still necessary for copying `google-services.json` into the correct location.
=> Simplified FCM implementation

plugin.xml
On iOS 10, push notification token generating can fail if `remote-notification` is not present in `Info.plist`.
=> Add 'remote-notification' background mode to Info.plist

plugin.xml, src/ios/AppDelegate+IntercomPush.m
This fixes the push plugin conflict described in https://github.com/intercom/intercom-cordova/issues/154 by intercepting push opened by the plugin and checking if its for Intercom.
I will also follow up with a change to our push plugin fork.
=> Push plugin compatibility

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
* Removed reliance on hooks for Android FCM support. Gradle is now used for the whole process.
* Improved iOS interoperability with `phonegap-plugin-push` (Fixes [#154](https://github.com/intercom/intercom-cordova/issues/154)).
* Automatically add `remote-notification` background mode to the app's `Info.plist` on iOS.
* Updated minimum Intercom for iOS version to [3.1.2](https://github.com/intercom/intercom-ios/releases/tag/3.1.2).
=> Release 3.1.1

plugin.xml, src/android/IntercomIntentService.java
Since we built this plugin, there have been many instances of people experiencing issues with Android push notifications when using other push providers (such as phonegap-plugin-push, OneSignal or UrbanAirship). The cause of this has been that Android will only notify one `GcmListenerService` instance of incoming notifications. Here are some of the issues: https://github.com/intercom/intercom-cordova/issues/165, https://github.com/intercom/intercom-cordova/issues/164, https://github.com/intercom/intercom-cordova/issues/139, https://github.com/intercom/intercom-cordova/issues/19, https://github.com/intercom/intercom-cordova/issues/3 and https://github.com/phonegap/phonegap-plugin-push/issues/1640.
The fix until now has been to fork `phonegap-plugin-push`. This is less than ideal and does …
=> Enable compatibility with other Android GCM providers

plugin.xml, scripts/checkForUpdate.js
This hook uses Github to check for new releases of Intercom. It will check at build time at most once every 48 hours.
This ensures that there will be no errors due to not running `pod repo update` and that Intercom for iOS is always update to date.
=> Add hook to check for iOS updates

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
* Fixed compatibility with other Android GCM providers (details are outlined in [#166](https://github.com/intercom/intercom-cordova/pull/166)). It is no longer necessary to use a fork of `phonegap-plugin-push`.
* Added hook to automatically update Intercom for iOS via CocoaPods (see [#168](https://github.com/intercom/intercom-cordova/pull/168)).
=> Release 3.1.2

plugin.xml, scripts/prepareCocoaPods.js
This is a follow up to https://github.com/intercom/intercom-cordova/pull/168.
While `checkForUpdate.js` ensures that Intercom is always up to date, this new hook makes sure that the local specs repo is fully updated when the plugin is installed. In practice that means that cryptic errors like `Error: pod: Command failed with exit code 1` can be avoided.
=> Add hook to ensure CocoaPods specs repo is up to date when installing the plugin

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/ios/IntercomBridge.m
* Added hook to ensure the local CocoaPods specs repo is up to date when installing the plugin (see [#170](https://github.com/intercom/intercom-cordova/pull/170)).
=> Release 3.1.3

CHANGELOG.md, README.md, package.json, plugin.xml, src/android/IntercomBridge.java, src/android/intercom.gradle, src/ios/IntercomBridge.m, www/intercom.js
* Added a new method to the API `intercom.setUserHash(userHash)` to support Identity Verification. This method replaces `intercom.setSecureMode(hmac, data)` which was used for our previous security feature Secure Mode.
* Updated Intercom for Android to 3.2.x.
* Updated Intercom for iOS to 3.2.x.
=> Release 3.2.0

.gitignore, circle.yml, src/android/build-extras-intercom.gradle
* Change unsafe versions of the Support Library to a known safe version
* Update CircleCI caching logic
* Exclude the `node_modules` from the Example from Git
=> Prevent unsafe versions of the Support Library being used

intercom-plugin/src/android/build-extras-intercom.gradle, intercom-plugin/src/android/intercom.gradle
This will log messages when:
* A `compileSdkVersion` of 25 or lower is used (we require 26)
* A `buildToolsVersion` of 25 or lower is used (we require 26)
* A Support Library of version 25 or lower is used (we require 26)
* A Firebase/Play Services library of version 10 or lower is used (we require 11)
=> Log errors when incompatible Android dependencies are used

intercom-plugin/src/android/build-extras-intercom.gradle
Should address this issue: https://github.com/intercom/intercom-cordova/issues/219
=> Ignore test dependencies when checking for incompatibilities

intercom-plugin/src/android/build-extras-intercom.gradle
There's a very slim chance that any Support Library dependencies will be declared outside of this config, and it appears to be the only one we can safely check: https://github.com/intercom/intercom-cordova/issues/219#issuecomment-344614403
=> Only check the `compile` configuration for dependencies

Example/README.md, Example/config.xml, Example/package-lock.json, Example/package.json, README.md, intercom-plugin/src/android/build-extras-intercom.gradle, intercom-plugin/src/android/intercom.gradle
This update includes breaking changes dictated by `cordova-android`'s 7.0.0 release as documented here: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html. When released, all Cordova project using the new release of `intercom-cordova` will need to use the `cordova-android` 7.0.0 or greater, which incidentally is bundled with Cordova 8.0.0 by default, though can be specified on older versions (tested on[ Cordova 7.1.0](https://github.com/apache/cordova-cli/releases/tag/7.1.0))
Will resolve many current build and GCM/FCM issues open on this repo. Will validate each issue fix individually upon release.
=> Update to Cordova Android 7.0.0

intercom-plugin/scripts/checkForUpdate.js
Fix issue with Intercom pod not being updated / installed when GitHub response was not 200 OK.
The issue is better described in #245
=> Fix issue with Intercom pod not being updated / installed when GitHub response was not 200 OK

intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle
When reading the GCM sender ID from `config.xml`, the Android OS XML parser can read it in as a string representation of a float, including scientific notation. This string is unusable as a sender ID.
To fix this, we read the sender ID directly from the `google-services.json` file if it's present. If the sender ID from the preferences is missing, or unusable, we return the ID from the JSON file.
This PR also includes some cleanup of the `IntercomBridge` class.
=> Fix GCM sender ID reading

intercom-plugin/src/android/intercom.gradle
This will allow apps using FCM Intercom push notifications to build when another Cordova plugin applies the Google Services Gradle plugin.
=> Allow FCM notifications without applying build plugin

intercom-plugin/src/android/build-extras-intercom.gradle
This matches the versions we currently support in the Android SDK
=> Update recommended build tool & library versions

CHANGELOG.md, README.md, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m
* Created fork of `phonegap-plugin-push` to allow it to work with this plugin: https://github.com/intercom/phonegap-plugin-push
* Allow FCM notifications without applying build plugin [#253](https://github.com/intercom/intercom-cordova/pull/253)
* Update recommended build tool & library versions [#252](https://github.com/intercom/intercom-cordova/pull/252)
* Remove broken support for multiple GCM libraries [#251](https://github.com/intercom/intercom-cordova/pull/251)
* Fix GCM sender ID reading [#250](https://github.com/intercom/intercom-cordova/pull/250)
* Change hook for checkForUpdate to be after_prepare [#249](https://github.com/intercom/intercom-cordova/pull/249)
=> Release version 5.1.0

intercom-plugin/src/android/intercom.gradle
This is needed for FCM notifications to be delivered when the build plugin is not used.
=> Include FCM libraries when building without build plugin

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m
* Include FCM libraries when building without build plugin [#257](https://github.com/intercom/intercom-cordova/pull/257)
=> Release version 5.1.1

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
**Enable mobile users to help themselves with the new mobile SDK for iOS and Android 🎉 😃**
The new Intercom mobile SDK brings the Messenger Home to your mobile applications. This means you can add messenger apps that allow your users to self-serve instead of starting a conversation. Users can now quickly access relevant help articles, review pinned content, and view product status in real time – all from the messenger home screen.
**API changes**
* `displayConversationsList` - Use `displayMessenger` instead.
These deprecated methods will still work, but will be removed in a future release.
=> Release 6.1.0

intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/ios/IntercomBridge.m, intercom-plugin/www/intercom.js
The changes allow to use cordova-plugin-intercom side by side with other plugins which also use GoogleServices. In my case I had an issue when using cordova-plugin-firebase at compile time.
Setting intercom-android-push-type to FCM-WITHOUT-BUILD-PLUGIN in config.xml solved the compile issue but then I was not able to send push notifications via Intercom.
My assumption was that the firebase token maybe wasn't sent to Intercom anymore. Therefore I added another function which allows to send this token manually from my Firebase component.
=> Add function to send firebase token to Intercom when intercom-android-push-type is set to FCM-WITHOUT-BUILD-PLUGIN

circle.yml
Similar with the changes made in a previous PR https://github.com/intercom/intercom-cordova/pull/277/files 
The command resource needs an update for nodejs in order to install npm during the publish job.
=> Fix CI for the publish job

CHANGELOG.md, Example/config.xml, Example/package-lock.json, Example/package.json, Example/www/js/index.js, README.md, circle.yml, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
* Upgraded to version 6.0.0 of the iOS and Android SDK.
* iOS 10 is now the minimum version of iOS that is supported by the Intercom iOS SDK.
* We have deprecated support for iOS 8 & 9.
* Android API level 21 (v5 - Lollipop) is now the minimum version of Android that is supported by the Intercom Android SDK.
* If your app still support API levels before 21 you'll need to bump minSdkVersion to 21 in order to use version 6+ of our SDK.
=> Release version 8.0.0

CHANGELOG.md, Example/config.xml, Example/package-lock.json, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/intercom.gradle
The Intercom Cordova plugin has been updated to use v7.1.1 of the iOS and Android SDK. We fixed a number of bugs in this release:
* Android:
* Fixed: An issue where buttons on the Messenger conversation card were not fully visible on small devices.
* Fixed: An issue where the conversation header wasn’t updates after a teammate reply.
* iOS:
* Improved: If your app does not request location permissions, you will no longer have to add a location permission string to your PList when using the Intercom iOS SDK.
=> Release 9.0.1

Example/config.xml, Example/package-lock.json, Example/package.json, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/intercom.gradle
* The Cordova plugin has been updated to be compatible with v7.2.0 of the Android SDK and v9.0.0 of Cordova Android.
* v7.2.0 of the Android SDK now uses Android X, and includes updates to the Gson and Firebase Messaging libraries it uses.
* In Cordova Android v9.0.0, the minimum Android API level is now API 22 (Android 5.1). The Cordova plugin's minimum version is now API 22 as well.
=> [AndroidX] Update SDK 7.2.0

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml
* The Cordova plugin has been updated to be compatible with v7.2.0 of the Android SDK and v9.0.0 of Cordova Android.
* v7.2.0 of the Android SDK now uses [Android X](https://developer.android.com/jetpack/androidx), and includes updates to the Gson and Firebase Messaging libraries it uses.
* In [Cordova Android v9.0.0](https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html), the minimum Android API level is now API 22 (Android 5.1). The Cordova plugin's minimum version is now API 22 as well.
=> Version 9.1.0

CHANGELOG.md, README.md, circle.yml, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/intercom.gradle
* The Intercom Cordova plugin has been updated to use v8.0.0 of the Intercom Android SDK as the latest version.
=> Version 9.1.1

CHANGELOG.md, Example/package-lock.json, Example/package.json, Example/www/css/index.css, Example/www/index.html, Example/www/js/index.js, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m, intercom-plugin/www/intercom.js
* The Intercom Cordova plugin has been updated to use v8.3.0 of the Intercom Android SDK and v8.1.0 of the iOS SDK as the latest version.
* New feature: You can now open an article or Mobile Carousel programmatically in your app. We have added two new methods to our API to enable this, [displayArticle](https://developers.intercom.com/installing-intercom/docs/cordova-phonegap-configuration#section-present-an-article-programmatically) and [displayCarousel](https://developers.intercom.com/installing-intercom/docs/cordova-phonegap-configuration#section-present-a-carousel-programmatically).
* Updated to cordova-ios 6.1.1.
=> Release 9.3.0

CHANGELOG.md, Example/www/index.html, Example/www/js/index.js, README.md, circle.yml, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/HelpCenterCollectionContentModel.java, intercom-plugin/src/android/HelpCenterCollectionModel.java, intercom-plugin/src/android/HelpCenterCollectionSectionModel.java, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/ICMHelpCenterArticle+DictionaryConversion.h, intercom-plugin/src/ios/ICMHelpCenterArticle+DictionaryConversion.m, intercom-plugin/src/ios/ICMHelpCenterArticleSearchResult+DictionaryConversion.h, intercom-plugin/src/ios/ICMHelpCenterArticleSearchResult+DictionaryConversion.m, intercom-plugin/src/ios/ICMHelpCenterCollection+DictionaryConversion.h, intercom-plugin/src/ios/ICMHelpCenterCollection+DictionaryConversion.m, intercom-plugin/src/ios/ICMHelpCenterCollectionContent+DictionaryConversion.h, intercom-plugin/src/ios/ICMHelpCenterCollectionContent+DictionaryConversion.m, intercom-plugin/src/ios/ICMHelpCenterSection+DictionaryConversion.h, intercom-plugin/src/ios/ICMHelpCenterSection+DictionaryConversion.m, intercom-plugin/src/ios/IntercomBridge.h, intercom-plugin/src/ios/IntercomBridge.m, intercom-plugin/www/intercom.js
* We have redesigned the Help Center for mobile apps. ✨
* New UI, optimized specifically for mobile apps and small screens
* Type-ahead search to help users find answers quicker than ever
* Control whether users open up a specific collection of articles, a group of collections, or specific search results
* Localization - with right to left language display
* Accessibility support: screen readers, dynamic font sizes, and keyboard navigation - to support all end users
* New Help Center Data API that enables you to build your own help center UI, enabling a much deeper and custom integration into your app.
Improvements and bug fixes
* Fixed an issue where the special notice message would not display.
* `hideMessenger()` has now been deprecated and removed. Please use `hideIntercom()` instead. …
=> Release 10.0.0

CHANGELOG.md, README.md, intercom-plugin/package.json, intercom-plugin/plugin.xml, intercom-plugin/src/android/IntercomBridge.java, intercom-plugin/src/android/intercom.gradle, intercom-plugin/src/ios/IntercomBridge.m
In https://github.com/intercom/intercom-cordova/pull/306 we allowed a fuzzy match for the Android SDK. This stopped resolving dependencies of the SDK transitively. Setting explicit versions of the dependencies here fixes building the Example app
=> Explicitly set Android version as 10.1.0

CHANGELOG.md, intercom-plugin/package-lock.json, intercom-plugin/package.json, intercom-plugin/plugin.xml
🐛 Bug Fixes
* Now sets the minimum deployment target in the `plugin.xml` for iOS to avoid collisions with other plugins.
=> Release 14.0.2
